/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zyh_pro_palettes_main_core_D2DPalette */

#ifndef _Included_com_zyh_pro_palettes_main_core_D2DPalette
#define _Included_com_zyh_pro_palettes_main_core_D2DPalette
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    createD2D
 * Signature: (Ljava/awt/Frame;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_createD2D
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_cleanup
  (JNIEnv *, jobject);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    beginPaint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_beginPaint
  (JNIEnv *, jobject);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    endPaint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_endPaint
  (JNIEnv *, jobject);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    drawBitmap
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_drawBitmap
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    drawText
 * Signature: (Ljava/lang/String;IIIII)V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_drawText
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    fillRect
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_fillRect
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    rect
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_rect
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    oval
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_oval
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    fillOval
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_fillOval
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

/*
 * Class:     com_zyh_pro_palettes_main_core_D2DPalette
 * Method:    line
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_com_zyh_pro_palettes_main_core_D2DPalette_line
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
